### PR TITLE
[WIP] Private/transaction notes

### PR DESCRIPTION
**Pull request by jdonkervliet**
Hi all,

This is a WIP PR that contains the work of Tim and me after an extensive pair programming session.
This PR adds a feature to Syncany. It allows for pipelined file indexing and uploading. Currently, this is done completely sequentially. A direct consequence of this is high memory usage and low performance. Hence the PR.

There are quite some technical changes. Most classes that we touched needed significant restructuring before we could add any new code. Please take a good look at the changes and let me know whenever you see something that you feel could me done better/cleaner/shorter. I will also do this, but for now I'm calling it a day.

So far, no tests have been updated and no documentation has been written. We are aware of these two issues and are working on them.

Thanks for any/all feedback!

### CODE REVIEW

**Comment by thegeman** [comment]
I fixed several bugs and I now believe that the "good weather scenario" of splitting a large volume of files/data into multiple transactions works properly. I added an integration test that checks for this scenario.

What still needs to be done:
- [ ] Clean up the code.
- [ ] Add scenario tests for the first/last/any transaction failing to check if the remote remains in a valid state (having only some files updated is acceptable, having files partially updated is not).
- [ ] Add scenario tests for the first/last/any transaction failing and then resuming to check if the resulting history is any different from a first-time successful operation.
- [ ] I do not yet grasp the internals of the deduplication, so we need to verify with the Syncany team if our approach does not prevent the deduplicater from comparing all chunks.

@jdonkervliet, do you think we should cc Pim to ask for some feedback?

**Comment by jdonkervliet** [comment]
Looks very good. @pimotte, what do you think of our progress?

**Comment by pimotte** [comment]
Couple of thoughts: 
- General concept is looks very clean:D
- The configurability of the limit should probably in UpOperationOptions, since it only affects Up.
- With respect to resuming: Am I reading correctly that we resume all indexed transactions, if we find (on the remote) exactly the one that was in progress when the connection dropped? Can we document the behavior we ended on in some comments?
- Jesse, do you have any objections to changing your `@author`-tags to include your last name? (For consistency.)

Ninja-edit: Also, don't forget to add any tests you add to the relevant TestSuite.

**Comment by thegeman** [comment]
Pim, thanks for the thoughts! To address your comments:
- We will move the limit configuration to UnOperationOptions. I was not sure where to put it.
- How resuming currently works: If at any point during a sequence of transactions a single transaction fails, we serialize that transaction and any transactions after it. This means that we complete the indexing/deduplication process to ensure that we use the same "change set" the next time a `sync up` is run. When we resume, there may be zero or one "resumable transactions" (a transaction that was in progress and is partially completed), and any number of "pending transactions" (for which the multichunks are cached locally, but transfer has not yet commenced). We will document this in the UnOperation javadoc.
- In general, Javadoc and `@author` tags need to be added where appropriate.

After addressing these issues, shall we open a PR upstream to discuss with Philip?

**Comment by pimotte** [comment]
Sounds good:)

**Comment by jdonkervliet** [comment]
I'm gonna close this and open a PR at Syncany's repo.

**Comment by jdonkervliet** [comment]
Sure, I can get them back. 

image

**Pull request closed without merging**
